### ISSUE TITLE
SUGGESTION: Lock plugin versions inside ngCordova wrapper

### ISSUE THREAD

**Issue by nraboy** [driftyco/ng-cordova#915] opened 2015-08-04 22:01 UTC
So I haven't thought of how to do this really, but I know it is possible and I think it would solve most of the reoccurring issue tickets that I read about.

There are 60+ external Apache Cordova plugins being wrapped in ng-cordova.  These plugins can introduce breaking changes at any given time if the wrapper is not updated to accommodate at the same time.

I propose including an ng-cordova.properties file and added CLI functionality to allow contributors to specify the plugin commit hash that works for the given version of the code.

**For example:**

ng-cordova is on commit hash 1234 and it has support for plugin x.  However, plugin x has just changed since committing 1234.  When users install plugin x, they are going to get the latest version unless they know of the breaking change and choose to use an older version.

**Solution:**

Through JSON or some kind of XML map, provide the plugin x and include the plugin x hash that works for commit 1234 of ng-cordova.  Then through this theoretical new CLI feature to install Ionic plugins, it references this ng-cordova map and downloads the correct version of the plugin.  Maybe Gulp can do this.  I don't know.  Maybe run something like `ionic plugin install plugin-x --ngcordova`

I think this will make people less likely to have to scramble to correct breaking change introductions.

Let me know if any of this doesn't make sense.

**Comment by mhartington** [comment] 2015-08-04 22:31
Hmm, @gortok and I started talking about this in https://github.com/driftyco/ng-cordova/issues/873 , it would require some work but I think it would be possible. 

A lot of this would have to depend on how cordova is handling the move npm. 

http://plugins.cordova.io/npm/index.html

So there is an api that we could leverage that to get the cordova plugins and their plugin version. 
Again this would require some work to figure out how they're doing it and if we would need to update ngcordova's site.

**Comment by nraboy** [comment] 2015-08-04 23:34
I think #873 is similar, but not the same.  In that other ticket I believe you guys are referring to plugin compatibility between versions of Apache Cordova.  In my ticket I am referring to plugin compatibility between versions of ngCordova.

If Apache introduces changes tomorrow for the Camera plugin, will the ngCordova wrapping code continue to function.  Maybe, and maybe not.  By pairing a specific version of every plugin to the latest version of ngCordova I think we can get around that.  Not everyone uses tags so I think commit hashes would work better.

Opinions?

**Comment by barryvdh** [comment] 2015-08-06 12:49
You could think about splitting up the repositories and let Bower (or npm etc) handle it.

So 1 'core' package with just the shared stuff. Then for each plugin a seperate repository, which requires the core package.

This does make it more work to maintain, because every repo has a lot of files, but it make it easy to install with Bower. Eg. I just want the push plugin:

`$ bower install ng-cordova-push`

That loads the push plugin + core. If I later on also want geo: `$ bower install ng-cordova-geo` or something.

If push moves to a different Cordova plugin, we can use a new major version. `1.x` for the old version, `2.x` for the new one. If there is a breaking change in one of the plugins, we can just require them seperate.

This large repo is easy to maintain, but you can't just set a fixed version on just 1 plugin..

**Comment by gortok** [comment] 2015-08-06 13:03
@barryvdh I like this idea because it would also show the relative popularity of each plugin. As it stands right now all plugins are equally included, meaning that we don't really know if there's one user of a plugin or a thousand.  By putting these wrappers in different Repos; we'd have a better sense of which are used and which are just (and should be) abandoned.  The downside (of course) is from a maintenance standpoint; because I'd be subscribed to 60+ repos to make changes. That could get ugly fast. 

That said, If it makes it easier to de-lineate which plugins are supported by which version of Cordova /  ngCordova, then I'm all about it.  

I'd rather a one-repo different branches for versions; but even that has its own issues; as does keeping it all in one repo yet having version files as metadata and having the build system create all plugins which are compatible with each version.

**Comment by barryvdh** [comment] 2015-08-06 13:08
Yeah you would get more repo's to watch, but the amount of issues would probably be the same ;)
You could also add more maintainers for just 1 repo, keep the issues organised per plugin and set an example so that other people can just make their own plugins on their own repo if they want.

**Comment by gortok** [comment] 2015-08-06 13:09
@barryvdh  I don't quite understand your last comment; can you expand on it? 

>  and set an example so that other people can just make their own plugins on their own repo if they want.

**Comment by barryvdh** [comment] 2015-08-06 13:15
Right now, you just maintain all the plugins right?

So for the new push plugin (#919), instead of creating a PR, I could just create my own repository, require the core package and use + maintain that. You guys could just link the package and reference it in some build package if you must.

Or if it's popular enough, transfer it to the ng-cordova organisation. (Which you would need to create, so you have `ng-cordova/core`, `ng-cordova/push` etc, instead of `driftyco`

**Comment by gortok** [comment] 2015-08-06 13:29
@barryvdh  That makes sense. One reason we don't do that currently are when things like the oAuth module are changed and regression, people could blame us even though we have no control over that.  If there were separate repos, I'd probably insist on keeping a small group of maintainers around them with either DriftyCo or Jewelbots organizational control (or a separate organization created for this).

@mlynch has stated publicly that the next version of ngCordova won't rely on Angular Promises and won't be tied to angular 1.x; and that's awesome -- except that there will be businesses (I'm thinking of Jewelbots, but there are probably others) that won't upgrade right away, so we may have months or a year of people still relying on ngCordova, and I don't want to leave them out in the cold.

When you have an App that you're using to push business revenue; it becomes very costly to rewrite that app because a new version came out; and the more I look at talks of Angular2, Ionic2, and ngCordova2, the more I see no easy upgrade path; which is problematic for businesses.

I say all that to say that no matter what, I'm going to be around ngCordova 1.0 for a while yet (at least until the middle of next year); so any plans we have have to take into account that other businesses will be too.

**Comment by mhartington** [comment] 2015-08-06 14:08
I don't think we need to make separate repos for each plugin. The speed at which apache moves does give us a lot of time to test out plugins from Github directly to make sure that everything works so I'm not too concerned.

As far as future version of ngCordova goes, yes it will move to plain observables, but the benefit there is that the end user shouldn't have to change much in there code. All of the changes would be internal. People who reply on ngCordova won't notice a big change to the code they write. So when 2.0 of ngCordova does come around, it will mean the end of ngCordova 1 and no more angular watches, but there will be an easy migration. 

Closing this.

**Closed by mhartington** 2015-08-06 14:08 UTC

**Comment by barryvdh** [comment] 2015-08-06 14:13
It's not just the speed of Apacha, but also for each plugin.

What if Geo makes a new version, that breaks BC. And Push releases a new version that I can't use yet. If you update both plugins in this repo, I must either use the latest version for both, or the old version for both. You can't selectively choose..

**Comment by mhartington** [comment] 2015-08-06 14:18
At least for the official cordova plugins, there is a release process that each one goes through and then they get put to a vote. They all get tested to make sure they don't break the other plugins. 

If the geolocation plugin gets updated, we can be sure that it wont break another plugin.
