### ISSUE TITLE
PushPlugin is deprecated

### ISSUE THREAD

**Issue by sidlauskaslukas** [driftyco/ng-cordova#963] opened 2015-09-01 09:44 UTC
"This plugin is deprecated, i.e. it is no longer maintained. Going forward additional features and bug fixes will be added to the new phonegap-plugin-push repository." https://github.com/phonegap-build/PushPlugin

When the new plugin will be available in ng-cordova?

**Comment by gortok** [comment] 2015-09-01 14:31
I'm looking into it today. I'll let you know.

**Comment by shprink** [comment] 2015-09-02 16:19
Just found out myself. +1 thanks :)

**Comment by gortok** [comment] 2015-09-02 16:20
I'm writing the wrapper for this plugin today; shouldln't take too long.  It'll go into the next version.

**Comment by shprink** [comment] 2015-09-02 16:21
one word: AWESOME!

thanks

**Comment by mellinas** [comment] 2015-09-09 15:11
+1, it would be great, thanks :)

**Comment by paulogr** [comment] 2015-09-09 15:14
Waiting for it!!

**Comment by gortok** [comment] 2015-09-09 15:15
Debugging it now. Will push when it's ready.

**Comment by ronyrun** [comment] 2015-09-09 16:22
+1

**Comment by MateuszWilk** [comment] 2015-09-10 13:12
+1

**Comment by gortok** [comment] 2015-09-11 22:04
I had some trouble getting my Push Notifications working through Parse's service; hence the trouble.  That'll be a separate plugin; but for now here's the plugin I'm using. There's some cleanup I need to do before adding it in, but it's available here: https://github.com/Jewelbots/ng-cordova/

**Comment by gortok** [comment] 2015-09-11 22:05
When the docs are cleaned up and everything's added in, I'll submit a PR.

**Comment by fazermokeur** [comment] 2015-09-14 14:41
Thank you for your work @gortok 
How could we update and test the upgrade via bower? We currently use the 0.1.17-alpha, should we wait for the 0.1.21-alpha release, or is there any other way to do this?

**Comment by gortok** [comment] 2015-09-14 14:58
@fazermokeur It'll be going into dev-next shortly, and will be part of the 0.1.21-alpha release.

**Comment by ronyrun** [comment] 2015-09-14 20:59
:1:

**Comment by ronyrun** [comment] 2015-09-14 20:59
:+1:

**Comment by razmik** [comment] 2015-09-21 05:34
Appreciate for your work @gortok 

Possible to let me know when the new ngCordova plugin will be available for new phonegap-plugin-push which can be work with iOS 9 ?

Thanks in advance.

**Comment by gortok** [comment] 2015-09-21 11:29
@razmik it's available now if you use bower's branch resolution against 'Dev-next', I'm currently running against Dev-next for our production work. I'll likely push out a release Tuesday or Wednesday of this week, depending on feedback.

**Comment by paulogr** [comment] 2015-09-21 11:32
hi, plz. Is this new version compatible with Ionic Push Service? Thanks.

**Comment by gortok** [comment] 2015-09-21 11:36
@paulogr I'm not qualified to answer that. We have parse for our backend push (ionic push wasn't out yet) and I modified the push plugin to work with parse; I don't know if something similar works with the ionic push plugin or if you can use it out of the box. @mhartington?

**Comment by Slavrix** [comment] 2015-09-21 11:48
Hey @gortok just a question on how to use the $cordovaPushV5 correctly.
its saying that when i run $cordovaPushV5.register.then(onSucess); that there is no then, even though it is a promise.

im calling $cordovaPushV5.initialize(options);
first and i get a successful response from that, and i run the register inside the onSuccess function.

**Comment by Slavrix** [comment] 2015-09-25 04:18
in the dev-next branch, does the module.js need the 'ngCordova.plugins.push_v5' added to it for it to work correctly?

**Comment by razmik** [comment] 2015-09-28 10:51
@gortok Hi again, any updates on pushing next version to production soon? 

"I'll likely push out a release Tuesday or Wednesday of this week, depending on feedback."

**Comment by jskrzypek** [comment] 2015-09-30 08:13
@Gortok does your plugin only work with parse? This means that to use a different baas or something like node-apn I'll have to roll my own wrapper for the phonegap-push-plugin?

**Comment by gortok** [comment] 2015-09-30 12:56
the wrapper here works with the push plugin. i didn't have to change this wrapper on my own repo that allows for it to integrate with parse because parse requires changes to the underlying plugin to work, not the wrapper. I don't know what other BaaS's do, so I can't speak to their needs for the underlying plugin.

**Comment by alexklibisz** [comment] 2015-10-05 15:41
@gortok I'm a bit of a novice with this stuff. How would I get the specific build/version that incorporates this change? It looks like the last release on the releases page was in May.

**Comment by JerryBels** [comment] 2015-10-08 09:14
+1

**Comment by fazermokeur** [comment] 2015-10-08 13:02
If you're using bower, you could install specific version using #numVersion behind the plugin name:
```
bower install ngCordova#0.1.20-alpha --save-dev
```

**Comment by raphaeldas** [comment] 2015-10-12 07:34
Hi, i'm new with cordova, angular and that stuff. will there be an instruction in the ngcordova docs soon?

**Comment by philmerrell** [comment] 2015-10-28 17:13
Is there an update on this or an ETA for when it will be merged in?  Is there something holding it back?

**Comment by gortok** [comment] 2015-10-28 17:22
@philmerrell Was hoping for more feedback than just my usage of it.

**Comment by philmerrell** [comment] 2015-10-28 17:30
@gortok Cool.  I'll lend a hand.  I'm currently implementing Push Notifications in an Ionic app using Amazon SNS.  I'll let you know how it goes.

**Comment by jskrzypek** [comment] 2015-10-29 09:34
@philmerrell, nice! We're building the stack :beers:

**Comment by fazermokeur** [comment] 2015-10-29 12:49
@gortok We use your fix from and it works fine \o/
The only point is that we don't receive error message whenit fails to register app when testing on IOS emulator. Not a major point, it could be specified in the doc.

**Comment by philmerrell** [comment] 2015-10-29 21:20
@jskrzypek :beers: cheers!

@gortok: It works great. Successfully tested on both Android and iOS.  The underlying plugin has changed enough to where example code may need to be updated, but maybe you've already done that, I haven't looked.  

The biggest differences, which I'm sure you're well aware of, are sending one options object (rather than a platform specific object) when initializing:
```js 
var options = {
   "android": { "senderID": "1111111" },
   "ios": { "alert": true, "badge": true, "sound": true}
};

$cordovaPush.initialize(options);
```
Also, the `register` method on Android responds with a registration ID now, which is awesome.  It used to respond with simply "OK" and you'd get the registration ID through a switch statement on the `$cordovaPush:notificationReceived` event.

The only thing I noticed is there's a few missing (iOS only) methods: `push.getApplicationIconBadgeNumber` and `push.finish`.

**Comment by evgd** [comment] 2015-11-01 21:39
Hi @gortok,
Thank you for your integration with new push plugin! 
I tested it and I was a bit confused with implementation...
Here is my PR.
I wanted to keep it simple and merged "initialize" and "register" method because in common case you will call them sequentially.
Possible use case of "initialize" without "register" - unregistration but it's not the case with current push plugin - https://github.com/phonegap/phonegap-plugin-push/issues/208.
Otherwise there is chance to miss "registrationId" as "PushNotification.init" registers on initialization:
```javascript
   setTimeout(function() {
       exec(success, fail, 'PushNotification', 'init', [options]);
   }, 10);
```
Register resolves with RegistrationId(token), rejects with registration error, subscribes to "notificationReceived" and "error" (as per current state of Push Plugin code errors triggers only during registration).

"onNotification" and "onError" methods - no need to call them, we can subscribe on "registration" to not miss "$cordovaPushV5:notificationReceived" and "$cordovaPushV5:errorOccurred".
```javascript
onNotification : function () {
// It's just subscription and can be done on register call.
    $timeout(function () {
      push.on('notification', function (notification) {
        $rootScope.$emit('$cordovaPushV5:notificationReceived', notification);
  });
});
```

Example for this PR:
```javascript
$rootScope.$on('$cordovaPushV5:notificationReceived', function (event, notification) {
    // ...
});

$rootScope.$on('$cordovaPushV5:errorOccurred', function (event, error) {
    // ...
});

$cordovaPushV5.register(options).then(function (token) {
    // ...
}, function (error) {
    // ...
});
```

**Comment by philmerrell** [comment] 2015-11-02 16:59
@evgd 

I totally see what your saying in terms of merging the 'init' and 'registration' methods, but since this is a wrapper for the 'phonegap-plugin-push', I'd personally like to see consistency between the methods in the plugin and the ngCordova wrapper.

I think it could also cause confusion to have the wrapper diverge in functionality from the plugin, but that's just my 2 cents.  Often I find myself reading the original plugin's documentation.

**Comment by evgd** [comment] 2015-11-02 22:12
@philmerrell 
Thank you for feedback. I agree with you that there is inconsistent with phonegap-plugin-push API. I thought that it would be handy to have "init" and "registration" in single method. We should consider that phonegap-plugin-push API consists of "init" method and "registration", "notification" and "error" events which means to keep it fully consistent there should be only "init" and "$cordovaPushV5:registrationId" event. I think some deviations is acceptable if they are well documented. As from my experience, I started using push plugin right from ngCordova examples and then, just to know how it works, checked push plugin documentation.
For me either one or two methods will look fine. But there is also other changes from PR aimed to prevent missing events(1), missed digest(2) and just to not force write sequence "$cordovaPushV5.onNotification(); $rootScope.$on('$cordovaPushV5:notificationReceived', ...);" that can be made implicitly (3).
Below original implementation with comments on points.
```javascript
// (3) it just subscribes to "push" events. If you don't want them just don't listen '$cordovaPushV5:notificationReceived' rootScope event.
onNotification : function () { 
// (2) no need of timeout here because it doesn't touch scope.
	$timeout(function () { 
	  push.on('notification', function (notification) {
// (2) but here we will want to wrap "$emit" with $timeout, $evalAsync or $apply to execute in "angular" context and force digest cycle.
	    $rootScope.$emit('$cordovaPushV5:notificationReceived', notification);
	  });
	});
}
```
With (1) it's not likely to happen if you know that "init" and "register" must be called sequentially (no postpone of "register" execution). Somebody can think that it's OK to init service at startup and register after some user interactions (like login, or press button, etc).
Another case for ideal latency world but it might happen if your have tons of watches for example:
```javascript
// this initializes "Registration" process. Check android code here https://github.com/phonegap/phonegap-plugin-push/blob/master/www/push.js#L60-L62 you have only 10ms to subsribe to events...
$cordovaPushV5.initialize() 
	.then(() => {
// I'm not aware of this behaviour and wanted to subscribe "notification" and "error" first, then make "register"
		$cordovaPushV5.onError(); // digest loop
		$cordovaPushV5.onNotification(); // digest loop
		$cordovaPushV5.register((registrationId) => ...); // are we still in 10ms range here?
	});
```

**Comment by raphaeldas** [comment] 2015-11-03 07:54
can somebody post a little example with the new syntax? I still don't understand what has changed, sorry!

**Comment by ronyrun** [comment] 2015-11-03 08:42
+1

**Comment by philmerrell** [comment] 2015-11-03 15:49
The main difference is that you have to pass in an `options` object to the `initialize` method first.  Then you can call `register` to get a registration id.

```js
var options = {
        "android": { "senderID": "12345" },
        "ios": { "alert": true, "badge": true, "sound": true }
      };
$cordovaPush.initialize(options);
```
Now you can do this: 

```js

$cordovaPush.register().then( (regId) => {
    console.log('Registration ID: ', regId);
});
```

**Comment by ronyrun** [comment] 2015-11-03 17:14
Thank you

**Comment by evgd** [comment] 2015-11-03 19:31
@ronyrun complete example for this branch
```javascript
module.run(function($cordovaPushV5, $rootScope) {

      var options = {
        "android": {
          "senderID": "12345"
        },
        "ios": {
          "alert": true,
          "badge": true,
          "sound": true
        }
      };

      document.addEventListener("deviceready", function() {

        $rootScope.$on('$cordovaPushV5:notificationReceived', (event, notification) => {
           // handle notification in application
        });

        $rootScope.$on('$cordovaPushV5:errorOccurred', (event, error) => {
          console.log('$cordovaPushV5:errorOccurred ' + error);
        });
        
        this.$cordovaPushV5.initialize(options);
        this.$cordovaPushV5.register().then(token => {
          console.log('$cordovaPushV5:REGISTERED', token);

          // below code required to configure $cordovaPushV5 notifications emitter. Don't pass function it's not handler.
          $cordovaPushV5.onError();
          $cordovaPushV5.onNotification();
        }, err => {
          console.error('$cordovaPushV5:REGISTER_ERROR', err);
        });
      }
});
```

**Comment by scripterkaran** [comment] 2015-11-10 09:14
$cordovaPushV5.register().then( function(token){
 //the code never comes here.... there is no log no error
} )

**Comment by evgd** [comment] 2015-11-10 09:41
@scripterkaran 
>there is no log no error
in console?

To check promise rejection you should change code to:
```javascript
$cordovaPushV5.register().then( function(token){}, function(){
console.log('error occurred');
} )
```

to check cordova push errors you should listen to "$cordovaPushV5:errorOccurred"

**Comment by scripterkaran** [comment] 2015-11-10 10:45
THIS will NOT work! 

```
module.factory(function($cordovaPushV5, $rootScope) {
    
     var iosConfig = {
             "alert": true,
             "badge": true,
             "sound": true
        };
     $cordovaPushV5.initialize(iosConfig);  //at run time only 
   
    return {
        serverRegister: function(){
            $cordovaPushV5.register().then(function(token){
                console.log('$cordovaPushV5:REGISTERED', token);
            }, function(err){
                console.error('$cordovaPushV5:REGISTER_ERROR', err);
            });
        }
    }
})

```

THIS WILL WORK 

```
module.factory(function($cordovaPushV5, $rootScope) {
 

    var iosConfig = {
        "alert": true,
        "badge": true,
        "sound": true
    };
    return {     
        serverRegister: function(){

            $cordovaPushV5.initialize(iosConfig);   // as a function instance
            $cordovaPushV5.register().then(function(token){
                console.log('$cordovaPushV5:REGISTERED', token);
            }, function(err){
                console.error('$cordovaPushV5:REGISTER_ERROR', err);
            });
        }
    }
})

```

**Comment by evgd** [comment] 2015-11-10 11:21
@scripterkaran yes, it's because you shouldn't call initialize prior to "deviceready" event. The above examples clearly showed this. 
Here is some details on this common issue - http://ngcordova.com/docs/common-issues/ 
Here is phonegap-plugin-push example - https://github.com/phonegap/phonegap-plugin-push/blob/master/example/www/js/index.js

**Comment by scripterkaran** [comment] 2015-11-10 11:30
I am using manual bootstrap of angular. So... My angular app is only initialised when device ready is called. So the problem is something else, but still it works in the latter snippet I posted.

Thank you for the links but this is of no help in this context.

```       
<script type="text/javascript">
            document.addEventListener('deviceready', function onDeviceReady() {
                angular.bootstrap(document, ['MyApp']);
            }, false);
        </script>

```

**Comment by seenimurugan** [comment] 2015-11-11 15:27
Thank you gortok, great plugin and great work. Just wonder why have you not included ngCordova.plugins.push_v5 module in the ngCordova.plugins module(version 0.1.22-alpha)? Thanks.

**Comment by gortok** [comment] 2015-11-11 15:38
@seenimurugan It's in v0.1.22-alpha, I'm not sure what you're referring to, can you link me to the file where it should be (but isn't)?

**Comment by seenimurugan** [comment] 2015-11-11 15:48
Hi @gortok thanks for the reply, I think ngCordova.plugins.push_v5 module in the ng-cordova.js file needs to be included in the 'angular.module('ngCordova.plugins', ['all_other_modules', 'ngCordova.plugins.push_v5'])' module's list as well. So that we can directly use the $cordovaPushV5 service without injecting the module manually. May be i am wrong/silly but just thought.

**Comment by gortok** [comment] 2015-11-11 15:50
@seenimurugan That's why I wanted you to link to the file; I couldn't find it to see where it should have been added. You're right, it' an oversight it wasn't added. I'll add it and increment the release so bower and NPM pick it up.

**Comment by gortok** [comment] 2015-11-11 15:57
This will be resolved when #1064 is merged, and I'll push out a new tag.   v0.1.23-alpha it will be. Some day I'll be able to make a build without having to make 3 builds to fix that build. Someday.

**Comment by gortok** [comment] 2015-11-11 16:19
pushed and merged. Let me know if you still run into an issue.

**Closed by gortok** 2015-11-11 16:19 UTC
Labels: enhancement

**Comment by seenimurugan** [comment] 2015-11-11 16:34
@gortok Perfect. Thanks.

**Comment by evgd** [comment] 2015-11-11 19:27
@gortok I see that final implementation has been agreed and ticket was closed. Did you have a chance to look at my PR and https://github.com/driftyco/ng-cordova/issues/963#issuecomment-153174075 ? Correct me if I'm wrong but in some cases current implementation can lead to unexpected behaviour or/and api not clear (for example onNotification, onError methods for subscription).

**Comment by vsafin-copart** [comment] 2015-11-23 07:36
@gortok 

Tried to use new $cordovaPushV5 and having issues.... dont see any log messages either. 
I am trying to make this work with Parse push service as well - would you be able to share sample project.

**Comment by andreialecu** [comment] 2015-11-23 13:40
I had similar problems to @scripterkaran with the promise never resolving on iOS and they were caused by some sort of incompatibility with the new push plugin and the old one. 

If I would install the new plugin while the deprecated one was still there, and then remove the deprecated one, the new one would stop working properly. I could confirm this in the logs from the device, where there would be an error about `Plugin 'PushPlugin' not found or is not a CDVPlugin`. I noticed something was wrong after putting a break point in the `init` function of `PushPlugin.m` in XCode and not seeing it trigger.

What did it for me was removing both plugins and then just adding the new one. It may also help removing the iOS platform and re-adding it.

**Comment by didbarbosa** [comment] 2016-01-07 11:21
Hello,
Could you guys please help me?
Notifications work well but when setting badgeNumber, the badge keeps displayed even if the app is relaunched/unistall etc...
I permanently have this badge...
How can I remove it?

Thanks

**Comment by smileapplications** [comment] 2016-01-13 02:27
Sorry but there is some sort of documentation for $cordovaPushV5 ? I cannot find it.

**Comment by gerhardcit** [comment] 2016-02-03 20:24
Documentation is limited, but this piece of code saved the day for me.
I'll repeat it just to make sure it is clear. Thx @ronyrun 

 $cordovaPushV5.initialize(options);
        $cordovaPushV5.register().then(token => {
          console.log('$cordovaPushV5:REGISTERED', token);

        **  // below code required to configure $cordovaPushV5 notifications emitter. Don't pass function it's not handler.**
          $cordovaPushV5.onError();
          $cordovaPushV5.onNotification();
        }, err => {
          console.error('$cordovaPushV5:REGISTER_ERROR', err);
        });

**Comment by aderowbotham** [comment] 2016-02-22 16:05
Given that https://github.com/phonegap-build/PushPlugin.git is deprecated – and causes a compile error with Cordova 6 in XCode – why does the ngCordova documentation [here](http://ngcordova.com/docs/plugins/pushNotifications/) still reference it?

**Comment by AllenConquest** [comment] 2016-03-15 16:18
How are we meant to call the push.finish() function to let the device know we have finished processing a background notification?

**Comment by AllenConquest** [comment] 2016-03-16 17:01
Similar to my previous comment, how can we call the push.getApplicationIconBadgeNumber() function ?

**Comment by mohanchalla** [comment] 2016-04-01 11:33
I am getting an error while injection  $cordovaPushV5 to app.run().

**Comment by samoka** [comment] 2016-07-30 17:51
Me too. 

Unknown provider: $cordovaPushV5Provider <- $cordovaPushV5

**Comment by jhlee8804** [comment] 2016-09-20 08:27
@samoka check follow link
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/EXAMPLES.md
