### ISSUE TITLE
cross-device link not permitted 

### ISSUE THREAD

**Issue by Syses** [driftyco/ng-cordova#867] opened 2015-07-06 12:31 UTC
when i  install the $cordovaActionSheet
the error  just follow
shell.js: internal error
Error: EXDEV, cross-device link not permitted 'C:\Users\ding\AppData\Local\Temp\git\1436184810259\demo'

how can i ....

**Comment by dennismuys** [comment] 2015-07-08 08:32
I have the same problem with the file-opener2 plugin.
This is my console output:

```
cordova plugin add https://github.com/pwlin/cordova-plugin-file-opener2.git
Fetching plugin "https://github.com/pwlin/cordova-plugin-file-opener2.git" via git clone
Repository "https://github.com/pwlin/cordova-plugin-file-opener2.git" checked out to git ref "master".
shell.js: internal error
Error: EXDEV, cross-device link not permitted '/var/folders/2l/6pn9cwj179d5f9rvnh0qc2nh0000gn/T/git/1436344003408/LICENSE'
    at Object.fs.renameSync (fs.js:543:18)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:77:8
    at Array.forEach (native)
    at Object._mv (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:53:11)
    at Object.mv (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/plugins.js:53:19
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
```

I am using cordova 5.1.1

**Comment by dennis-devoon** [comment] 2015-07-08 08:45
https://github.com/litehelpers/Cordova-sqlcipher-adapter/issues/9

as you can see it is a problem with cordova CLI 5.1.1 you can roll back to 4.3.0 and it will work

**Comment by BetaBugish** [comment] 2015-07-08 13:15
Same issue with the Cordova spinner dialog.
Pretty much the same log too.
```
Fetching plugin "https://github.com/Paldom/SpinnerDialog.git" via git clone
Repository "https://github.com/Paldom/SpinnerDialog.git" checked out to git ref "master".
shell.js: internal error
Error: EXDEV, cross-device link not permitted '/tmp/git/1436361192057/LICENSE'
    at Error (native)
    at Object.fs.renameSync (fs.js:636:18)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:77:8
    at Array.forEach (native)
    at Object._mv (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:53:11)
    at Object.mv (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/plugins.js:53:19
    at _fulfilled (/usr/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/cordova/node_modules/q/q.js:749:13)
```

**Comment by brodybits** [comment] 2015-07-13 09:19
Guys please do `npm uninstall -g cordova` (use `sudo` if you have to), make sure no other Cordova `npm` packages are installed, and try a fresh install of Cordova. If you continue to see problems please raise an issue on Cordova via https://issues.apache.org/jira/secure/Dashboard.jspa.

**Comment by jimutt** [comment] 2015-07-31 10:14
I'm getting the same issue when trying to run `cordova plugin add https://github.com/bcsphere/bluetooth.git`

**Comment by mhartington** [comment] 2015-08-04 20:53
Closing this as it is not an issue with ng-cordova, but a but with the cordova-cli
This probably has to do with the move of plugins to npm. 
Looks like the first plugin isn't on npm.

**Closed by mhartington** 2015-08-04 20:53 UTC

**Comment by softBarbarian** [comment] 2015-08-07 15:37
`npm install -g cordova@5.0.0` worked for me!

**Comment by elpalpitar** [comment] 2015-08-09 01:45
@softBarbarian  worked for me, too. Thanks a lot

**Comment by shulamit74** [comment] 2015-08-11 12:45
same when trying cordova plugin add https://github.com/jsHybugger/cordova-plugin-jshybugger.git
solved after npm install -g cordova@5.0.0
thanks!

**Comment by umar13893** [comment] 2015-08-13 10:19
npm install -g cordova@5.0.0 Its worked for me

**Comment by kewix** [comment] 2015-08-19 09:00
Thanks, npm install -g cordova@5.0.0 also finally worked for me :)

**Comment by joequah1** [comment] 2015-08-20 13:52
"npm install -g cordova@5.0.0"  works for me, thanks

**Comment by nathantsoi** [comment] 2015-08-25 16:16
5.2.0 (latest release), also appears to be working, so this fixed it for me: ```npm update -g cordova```

**Comment by mhartington** [comment] 2015-08-25 16:19
Confirming that 5.2 works as well. Please update your cordova version.

**Comment by jasdeepkhalsa** [comment] 2015-11-04 21:26
I can confirm this also works with the latest Cordova CLI 5.3.3. Updating with `npm update -g cordova` worked for me!
