### ISSUE TITLE
cordova.plugins not load

### ISSUE THREAD

**Issue by morcegon** [driftyco/ng-cordova#860] opened 2015-06-29 20:10 UTC
Hello, firstly thanks for the amazing work!

I'm very newbie on this. In a test with the barcode scanner plugin, every time I got this console error:
> undefined is not an object (evaluating 'cordova.plugins.barcodeScanner')

I remake the install steps a few times, but it's seems like the cordova.plugins dont work. Others plugins, like camera works fine. 

i'm testing with phonegap on iPhone 5s with IOS 8.3.

Thanks

This my app.js
```javascript
var exempleApp = angular.module('starter', ['ionic', 'ngCordova'])

.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if(window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
    }
    if(window.StatusBar) {
      StatusBar.styleDefault();
    }

    if ($window.cordova &&
        $window.cordova.plugins &&
        $window.cordova.plugins.barcodeScanner) {
      console.log('Plugin available');
    }
    else
    {
      console.log('nao');
    }

  });
});

exempleApp.controller('ExempleController', function($scope, $cordovaBarcodeScanner, $cordovaVibration, $cordovaCamera, $ionicPlatform){

  document.addEventListener("deviceready", function () {

    $scope.scanBarcode = function () {


      
      $cordovaBarcodeScanner.scan().then(function (imageData) {
        alert(imageData.text);
        console.log('Format '+imageData.format);
      }, function (error) {
        console.log('Um erro: '+error);
      });
     
    };

  }, false);

});
````

My index.html:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title></title>

    <link href="lib/ionic/css/ionic.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">

    <!-- IF using Sass (run gulp sass first), then uncomment below and remove the CSS includes above
    <link href="css/ionic.app.css" rel="stylesheet">
    -->

    <!-- ionic/angularjs js -->
    <script src="lib/ionic/js/ionic.bundle.js"></script>

    <!-- cordova script (this will be a 404 during development) -->
    <script src="lib/ngCordova/dist/ng-cordova.min.js"></script>
    <script src="cordova.js"></script>

    <!-- your app's js -->
    <script src="js/app.js"></script>
  </head>
  <body ng-app="starter" class="platform-ios">

    <ion-pane>
      <ion-header-bar class="bar-stable">
        <h1 class="title">Ionic Blank Starter</h1>
      </ion-header-bar>
      <ion-content ng-controller="ExempleController">
        <button class="button" ng-click="scanBarcode()">Tirar Foto</button>

        <img src="" alt="" id="myImage">
      </ion-content>
    </ion-pane>
  </body>
</html>
```

**Comment by DanailMinchev** [comment] 2015-07-01 10:44
Hi @morcegon ,

Do you wrap cordova calls like this:
```
$ionicPlatform.ready(function() {
      if ($window.cordova &&
          $window.cordova.plugins &&
          $window.cordova.plugins.barcodeScanner) {
        console.log('Plugin available');
      }
});
```

**Comment by morcegon** [comment] 2015-07-01 13:17
Hi @DanailMinchev ,

This is my app.js controller:

```javascript
exempleApp.controller('ExempleController', function($scope, $cordovaBarcodeScanner, $cordovaVibration, $cordovaCamera){

  document.addEventListener("deviceready", function () {

    $scope.scanBarcode = function () {

      $cordovaBarcodeScanner.scan().then(function (imageData) {
        alert(imageData.text);
        console.log('Format '+imageData.format);
      }, function (error) {
        console.log('Um erro: '+error);
      });

    };

  }, false);

});
```

**Comment by dangnelson** [comment] 2015-07-02 20:01
I'm having the same issue, but with the keyboard plugin.

    .controller('CameraCtrl', function($scope, Camera, $cordovaKeyboard) {
      $cordovaKeyboard.disableScroll(true);
      $cordovaKeyboard.hideKeyboardAccessoryBar(true);
     })

Getting error:
Error: undefined is not an object (evaluating 'cordova.plugins.Keyboard')

Tried wrapping the cordova call as was suggested above

**Comment by DanailMinchev** [comment] 2015-07-02 20:08
`$cordovaLocalNotification` also uses `$window.cordova.plugins` namespace for example `$window.cordova.plugins.notification.local.schedule`, but it is working for me and other plugins are wokring, too

**Comment by morcegon** [comment] 2015-07-02 20:21
Hey @DanailMinchev ,

I paste my app.js and index.html above. I'm using Ionic with ngCordova and follow the examples to install.

Thanks,

**Comment by DanailMinchev** [comment] 2015-07-02 20:21
@morcegon @dangnelson please try this two simple snippets:

1). Confirm `window.cordova` is available:
```
document.addEventListener("deviceready", function () {
  if (window.cordova) {
    console.log('window.cordova is available');
  } else {
    console.log('window.cordova NOT available');
  }
}, false);
```

2). Confirm `window.cordova.plugins` is available:
```
document.addEventListener("deviceready", function () {
  if (window.cordova && window.cordova.plugins) {
    console.log('window.cordova.plugins is available');
  } else {
    console.log('window.cordova.plugins NOT available');
  }
}, false);
```

**Comment by morcegon** [comment] 2015-07-02 20:27
@DanailMinchev ,

I've tested now and this is the log:
``` console
[phonegap] [console.log] window.cordova is available
[phonegap] [console.log] window.cordova.plugins NOT available
```

**Comment by DanailMinchev** [comment] 2015-07-02 20:54
@morcegon thanks! Very strange .. this confirms that any plugin in `window.cordova.plugins` namespace will not work.. No clue how to fix it, tough :(

Just a guess:
In your `app.js` you need to add `$window` in `.run(function($ionicPlatform) {`, because it is used without injecting it like this `.run(function($ionicPlatform, $window) {`
Try calling plugin directly (this probably won't work because `cordova.plugins` is undefined):
```
document.addEventListener("deviceready", function () {
  cordova.plugins.barcodeScanner.scan(function(result) {
    // ...
  }, function (err) {
    // ...
  });
}, false);
```
I can see you already created issue on plugin's repo https://github.com/wildabeast/BarcodeScanner/issues/292 which is the right place if it is related to cordova, not ngCordova wrapper

**Comment by dangnelson** [comment] 2015-07-02 21:03
I've got this at the top of my app.js:

    .run(function($ionicPlatform, $http, $rootScope, ngFB, $window) {
        $ionicPlatform.ready(function() {
	  
	  if ($window.cordova &&
          $window.cordova.plugins &&
          $window.cordova.plugins.Keyboard) {
             console.log('Plugin available');
          }
        })
    })

And these at the bottom:

    document.addEventListener("deviceready", function () {
     if (window.cordova) {
       console.log('window.cordova is available');
     } else {
    console.log('window.cordova NOT available');
     }
    }, false);

    document.addEventListener("deviceready", function () {
      if (window.cordova && window.cordova.plugins) {
        console.log('window.cordova.plugins is available');
      } else {
        console.log('window.cordova.plugins NOT available');
      }
    }, false);

and I'm getting this:
[Error] Error: undefined is not an object (evaluating 'cordova.plugins.Keyboard')
[Log] window.cordova is available (app.js, line 273)
[Log] window.cordova.plugins is available (app.js, line 281)
[Log] Plugin available (app.js, line 18)


Looks like everything's available, not sure what's going on.

**Comment by morcegon** [comment] 2015-07-02 21:17
@DanailMinchev thanks for your help.
I tried calling the plugin directly, but don`t work too. Its just the cordova.plugins the error core.

thanks.

**Comment by dangnelson** [comment] 2015-07-06 16:15
I was able to resolve the error by wrapping the call in $ionicPlatform:

	$ionicPlatform.ready(function() {
	   $cordovaKeyboard.disableScroll(true);
	   $cordovaKeyboard.hideAccessoryBar(true);
	});

But now I'm having an issue with the keyboard disable scroll command not working...

    $cordovaKeyboard.disableScroll(true);

**Comment by gortok** [comment] 2015-08-13 13:42
Closing as the initial issue brought up is not an ngCordova issue (turns out the $ionicPlatform.ready call was required).  @dangnelson If you can open a separate issue with a reproducible snippet for the $cordovaKeyboard.disableScroll() issue, we'll be happy to take a look.

**Closed by gortok** 2015-08-13 13:42 UTC

**Comment by dangnelson** [comment] 2015-08-13 13:58
The disable scroll issue I had ended up being a conflict with an auto focus which I've addressed in the keyboard plugin git. The wrap above did in fact solve my problem. Thanks
