### ISSUE TITLE
Problem using Facebook plugin

### ISSUE THREAD

**Issue by naveedse** [driftyco/ng-cordova#532] opened 2014-12-29 09:48 UTC
Hi,
I want to access facebook with cordova app so using facebook plugin. (anroid / ios app not web based authentication which im already doing using plugin here http://ngcordova.com/docs/plugins/oauth/)

http://ngcordova.com/docs/plugins/facebook/

i did as explained in the tutorial but got error

ReferenceError: facebookConnectPlugin is not defined

i added facebookConnectPlugin.js file but got error

Uncaught ReferenceError: require is not defined

not sure how to fix it

can anybody tell me how can i authenticate with facebook correctly

thanks

-Navi

**Comment by nandanrao** [comment] 2015-01-04 15:49
Hey Navi -- you should not need to add the facebookConnectPlugin.js manually, it's part of the plugin -- did you install the plugin as per the instructions here: https://github.com/Wizcorp/phonegap-facebook-plugin ?

**Comment by pbernasconi** [comment] 2015-01-04 18:23
Duplicate of #446

**Closed by pbernasconi** 2015-01-04 18:23 UTC

**Comment by sean-hill** [comment] 2015-01-08 18:34
Anyone got this to work during Web Dev since the recent update to the Facebook Plugin for ngCordova within the last little bit?

This updated facebookConnectPlugin.js file throws an error now since `cordova` isn't defined in my Chrome Browser.

https://github.com/Wizcorp/phonegap-facebook-plugin/blob/master/facebookConnectPlugin.js

**Comment by pbernasconi** [comment] 2015-01-08 18:35
@sean-hill check out this discussion : https://github.com/driftyco/ng-cordova/issues/446#issuecomment-69132485

**Comment by sean-hill** [comment] 2015-01-08 18:37
@pbernasconi You're the best, thanks.
