### ISSUE TITLE
Cordova Plugin File - this path has an invalid ":" in it.

### ISSUE THREAD

**Issue by machei** [driftyco/ng-cordova#704] opened 2015-03-26 15:01 UTC
Actually Cordova Plguin file (original) doesnt support like that file:\\, then remove it.

Error:
```
org.apache.cordova.file.EncodingException: This path has an invalid ":" in it.
```

https://github.com/apache/cordova-plugin-file/blob/67924cf9f679d3e6cbb05411f76f90405f36288c/src/android/LocalFilesystem.java#L123

My code:
```
c.checkDir(cordova.file.applicationDirectory,'article').then(function(a){console.log(a)}, function(a){console.log(a)})
```
-> errorcode : 5
```
c.checkDir('article', '').then(function(a){console.log(a)}, function(a){console.log(a)})
```
-> no error, 
-> DirectoryEntry {isFile: false, isDirectory: true, name: "", fullPath: "/", filesystem: FileSystem…}
-> NativeUrl: "file:///storage/emulated/0/article/"

http://ngcordova.com/docs/plugins/file/ <- updated? and correct? go check.

Same issue: https://github.com/driftyco/ng-cordova/issues/506

**Comment by machei** [comment] 2015-03-26 15:04
Same issue:
https://github.com/driftyco/ng-cordova/issues/506

**Comment by gortok** [comment] 2015-08-02 01:42
Since this is a dupe of #506, closing.

**Closed** 2015-08-02 01:42 UTC
